[General]            
AutoGeneratePasswordForNewEntries=false
AutoTypeDelay=15
AutoTypeStartDelay=150
BackupBeforeSave=true
# @TODO: Backup path
# BackupFilePathPattern=D:/DOCUMENTS/Passwords/backup/{TIME:yyyyMMddhh}.old.kdbx
URLDoubleClickAction=1

[Browser]
Enabled=true
BestMatchOnly=true
SearchInAllDatabases=true
UnlockDatabase=true
MatchUrlScheme=true

[GUI]
ApplicationTheme=dark 
ColorPasswords=true
MonospaceNotes=true
MovableToolbar=false

[PasswordGenerator]
AdditionalChars="!\"#$%&()*+,-./:;<=>?@[\\]_{|}~"
AdvancedMode=true
ExcludedChars=\xb0`\xb4\xa7'^
Length=20

[Security]
ClearClipboardTimeout=30
ClearSearch=true
IconDownloadFallback=true
LockDatabaseIdle=false
LockDatabaseMinimize=true

# [SSHAgent]
# Enabled=true
# UseOpenSSH=true

[FdoSecrets]
Enabled=true