{ lib, ... }:
let
  inherit (lib)
    concatStringsSep
    mkOption
    types
    ;

  components = [
    "waybar"
    "mako"
    "xwayland-satellite"
  ];

  mkSpawn = c: ''spawn-at-startup "${c}"'';
in
{
  flake.modules.homeManager.desktopEnvironment =
    { ... }:
    {
      config = {
        home.file.".config/niri/startup.kdl".text = ''
          // Generated by Nix. Do not edit; see modules/desktop/desktop-environment.nix.
          ${concatStringsSep "\n" (map mkSpawn components)}
        '';
      };
    };
    
  flake.modules.nixos.desktopEnvironment =
    { config, pkgs, ... }:
    let
      inherit (config.profile) user;
    in
    {
      options = {
        profile.user = {
          xkb.layout = mkOption {
            type = types.str;
            default = "us";
            description = "xkb keyboard layout";
          };
          xkb.variant = mkOption {
            type = types.str;
            default = "";
            description = "xkb keyboard variant";
          };
        };
      };

      config = {
        xdg.portal = {
          enable = true;
          extraPortals = [
            pkgs.xdg-desktop-portal-gtk
            pkgs.xdg-desktop-portal-gnome
          ];
          config = {
            common.default = [ "gtk" ];
            niri.default = [
              "gnome"
              "gtk"
            ];
          };
        };

        # @TODO: Look for other package combos with niri
        # https://github.com/niri-wm/awesome-niri
        # https://niri-wm.github.io/niri/Important-Software.html
        environment.systemPackages = [
          pkgs.mako
          pkgs.xwayland-satellite

          pkgs.lxqt.lxqt-policykit
          pkgs.brightnessctl
          pkgs.playerctl
          pkgs.alacritty
          pkgs.nautilus
          pkgs.wl-clipboard

          # Temporary until quickshell works
          pkgs.fuzzel
          pkgs.swaylock
          pkgs.swayidle
          pkgs.swaybg
          pkgs.libnotify
        ];

        # Temporary until quickshell works
        programs.waybar.enable = true;
        security.pam.services.swaylock = { };
        security.pam.services.sddm.enableGnomeKeyring = true;

        environment.sessionVariables = {
          NIXOS_OZONE_WL = "1";
          XKB_DEFAULT_LAYOUT = user.xkb.layout;
          XKB_DEFAULT_VARIANT = user.xkb.variant;
          TERMINAL = "alacritty";
        };

        programs.niri.enable = true;
        programs.dconf.enable = true;
        security.polkit.enable = true;
        services = {
          gnome.gnome-keyring.enable = true;
          xserver = {
            enable = true;
            xkb.layout = user.xkb.layout;
          };
        };
      };
    };
}