{ lib, ... }:
let
  components = [
    "waybar"
    "mako"
    "xwayland-satellite"
  ];

  mkSpawn = c: ''spawn-at-startup "${c}"'';
in
{
  flake.modules.homeManager.desktopEnvironment =
    { ... }:
    {
      config = {
        home.file.".config/niri/startup.kdl".text = ''
          // Generated by Nix. Do not edit; see modules/desktop/desktop-environment.nix.
          ${lib.concatStringsSep "\n" (map mkSpawn components)}
        '';
      };
    };

  flake.modules.nixos.desktopEnvironment =
    { pkgs, host, ... }:
    let
      inherit (host) locale;
    in
    {
      config = {
        xdg.portal = {
          enable = true;
          extraPortals = [
            pkgs.xdg-desktop-portal-gtk
            pkgs.xdg-desktop-portal-gnome
          ];
          config = {
            common.default = [ "gtk" ];
            niri.default = [
              "gnome"
              "gtk"
            ];
          };
        };

        # @TODO: Look for other package combos with niri
        # @TODO: Clean this up
        # https://github.com/niri-wm/awesome-niri
        # https://niri-wm.github.io/niri/Important-Software.html
        environment.systemPackages = [
          pkgs.mako
          pkgs.xwayland-satellite

          pkgs.kanshi
          pkgs.lxqt.lxqt-policykit
          pkgs.brightnessctl
          pkgs.playerctl
          pkgs.alacritty
          pkgs.nautilus
          pkgs.wl-clipboard
          pkgs.bibata-cursors

          # Temporary until quickshell works
          pkgs.fuzzel
          pkgs.swaylock
          pkgs.swayidle
          pkgs.swaybg
          pkgs.libnotify
        ];

        services.udev.packages = [
          pkgs.brightnessctl
        ];

        # Temporary until quickshell works
        programs.waybar.enable = true;
        security.pam.services.swaylock = { };

        environment.sessionVariables = {
          NIXOS_OZONE_WL = "1";

          XKB_DEFAULT_LAYOUT = locale.xkbLayout;
          XKB_DEFAULT_VARIANT = locale.xkbVariant;
          XCURSOR_THEME = "Bibata-Modern-Ice";
          XCURSOR_SIZE = "24";

          TERMINAL = "alacritty";
        };

        programs.niri.enable = true;
        programs.dconf.enable = true;
        security.polkit.enable = true;

        services = {
          gnome.gnome-keyring.enable = lib.mkForce false;
          xserver.enable = true;
        };
      };
    };
}
