{ lib, ... }:
let
  inherit (lib) mkForce concatStringsSep;

  components = [
    "mako"
    "xwayland-satellite"
  ];

  mkSpawn = c: ''spawn-at-startup "${c}"'';
in
{
  flake.modules.homeManager.desktopEnvironment = {
    config = {
      home.file.".config/niri/startup.kdl".text = ''
        // Generated by Nix. Do not edit; see modules/desktop/desktop-environment.nix.
        ${concatStringsSep "\n" (map mkSpawn components)}
      '';
    };
  };

  flake.modules.nixos.desktopEnvironment =
    { pkgs, locale, ... }:
    let
      # Perceived brightness is roughly logarithmic, so step by a fixed ratio
      # rather than a fixed percentage of maximum: the same 5% is invisible at
      # the top of the range and a third of the range at the bottom.
      backlight = pkgs.writeShellApplication {
        name = "backlight";
        runtimeInputs = [
          pkgs.brightnessctl
          pkgs.gawk
        ];
        text = ''
          step=1.25
          floor=1

          cur=$(brightnessctl --class=backlight get)
          max=$(brightnessctl --class=backlight max)

          new=$(awk -v c="$cur" -v m="$max" -v s="$step" -v f="$floor" \
                    -v d="''${1:-up}" '
            BEGIN {
              lo = m * f / 100
              if (lo < 1) lo = 1

              n = (d == "down") ? c / s : c * s

              # Ratios stall on small numbers; guarantee one raw unit of travel.
              if (d == "up" && n - c < 1) n = c + 1
              if (d == "down" && c - n < 1) n = c - 1

              if (n < lo) n = lo
              if (n > m)  n = m

              printf "%d", n + 0.5
            }')

          brightnessctl --class=backlight set "$new"
        '';
      };
    in
    {
      config = {
        xdg.portal = {
          enable = true;
          extraPortals = [
            pkgs.xdg-desktop-portal-gtk
            pkgs.xdg-desktop-portal-gnome
          ];
          config = {
            common.default = [ "gtk" ];
            niri.default = [
              "gnome"
              "gtk"
            ];
          };
        };

        # @TODO: Look for other package combos with niri
        # @TODO: Clean this up
        # https://github.com/niri-wm/awesome-niri
        # https://niri-wm.github.io/niri/Important-Software.html
        environment.systemPackages = [
          pkgs.mako
          pkgs.xwayland-satellite

          pkgs.kanshi
          pkgs.lxqt.lxqt-policykit
          pkgs.brightnessctl
          backlight
          pkgs.playerctl
          pkgs.alacritty
          pkgs.nautilus
          pkgs.wl-clipboard
          pkgs.bibata-cursors

          # Temporary until quickshell works
          pkgs.fuzzel
          pkgs.swaylock
          pkgs.swayidle
          pkgs.swaybg
          pkgs.libnotify
        ];

        services.udev.packages = [
          pkgs.brightnessctl
        ];

        # Temporary until quickshell works
        programs.waybar.enable = true;
        security.pam.services.swaylock = { };

        environment.sessionVariables = {
          NIXOS_OZONE_WL = "1";

          XKB_DEFAULT_LAYOUT = locale.xkb.layout;
          XKB_DEFAULT_VARIANT = locale.xkb.variant;
          XCURSOR_THEME = "Bibata-Modern-Ice";
          XCURSOR_SIZE = "24";

          TERMINAL = "alacritty";
        };

        programs.niri.enable = true;
        programs.dconf.enable = true;
        security.polkit.enable = true;

        services = {
          gnome.gnome-keyring.enable = mkForce false;
          xserver.enable = true;
        };
      };
    };
}
