[[items]]
file = "~/.config/alacritty/alacritty.toml"
template = "alacritty"

[[items]]
file = "~/.config/niri/colors.kdl"
template = "niri"
rewrite = true

[[items]]
file = "~/.config/nix/zen.json"
template = "nix"
subtemplate = "zen"
rewrite = true