#
# refind.conf
# Configuration file for the rEFInd boot menu
# https://rodsbooks.com/refind/configfile.html
#

timeout 20
use_nvram false
scanfor internal,manual

# @TODO: See other default directories we dont want
dont_scan_dirs EFI/nixos-boot

menuentry "NixOS" {
    icon themes/rEFInd-minimal-dark/icons_dark/os_nixos.png
    loader /EFI/nixos-boot/grubx64.efi
}

include themes/rEFInd-minimal-dark/theme.conf
