#
# refind.conf
# Configuration file for the rEFInd boot menu
# https://rodsbooks.com/refind/configfile.html
#

timeout 20
use_nvram false
scan_delay 0
use_graphics_for osx,linux

scanfor internal,external,optical,manual
dont_scan_dirs EFI/nixos,EFI/NixOS-boot

showtools shell,memtest,about,reboot,shutdown,firmware

# Manual NixOS boot entry
menuentry "NixOS" {
    icon /EFI/refind/icons/os_linux.png
    loader /EFI/NixOS-boot/grubx64.efi
}
