#
# refind.conf
# Configuration file for the rEFInd boot menu
# https://rodsbooks.com/refind/configfile.html
#

timeout 20
use_nvram false
scan_delay 0
use_graphics_for osx,linux

scanfor manual
showtools shell,memtest,about,reboot,shutdown,firmware

# Boot entries
menuentry "NixOS" {
    icon /EFI/refind/themes/rEFInd-darkflake/icons/os_nixos.png
    loader /EFI/NixOS-boot/grubx64.efi
}

# Theme
include themes/rEFInd-darkflake/theme.conf
