[General]
background=
backgroundFill=#0c0c12
backgroundFillMode=fill

font=Inter
basicTextColor=#a5b6cf
hideCursor=false

passwordCharacter=•
passwordMask=true
passwordFontSize=28
passwordInputWidth=0.22
passwordInputRadius=12
passwordInputBackground=#1c1e27
passwordInputBorderWidth=1
passwordInputBorderColor=#323947
passwordTextColor=#e6e8ee
passwordCursorColor=#8aa2ff
passwordInputCursorVisible=true
cursorBlinkAnimation=true

wrongPasswordBorderColor=#ff6b7a
wrongPasswordBorderRadius=12

showUsersByDefault=true
showUserRealNameByDefault=false
usersFontSize=16

showSessionsByDefault=true
sessionsFontSize=12

helpFont=Inter
helpFontSize=11
